global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.exmail.qq.com:587'
  smtp_from: 'ewtnotice@mistong.com'
  smtp_auth_username: 'ewtnotice@mistong.com'
  smtp_auth_password: 'Ewt360.com'
  smtp_require_tls: true
templates:
  - '/usr/local/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: default-receiver
receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'ligang2269@mistong.com'

inhibit_rules: 
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
