global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.exmail.qq.com:587'
  smtp_from: 'ewtnotice@mistong.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true
templates:

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 3m
  receiver: webhook

receivers:
- name: webhook
  webhook_configs:
  - url: http://localhost:8060/dingtalk/ops_dingding/send 
    send_resolved: true
inhibit_rules: 
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
